# Generated by Django 2.2.17 on 2025-08-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='topLevelDomain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
